///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsAdVideo1 = 'assets/ad_video1.mp4';
  static const String assetsAdVideo2 = 'assets/ad_video2.mp4';
  static const String assetsLogoIcon = 'assets/logo_icon.png';
  static const String typeLegraise = 'assets/type/legraise.png';
  static const String typeLunge = 'assets/type/lunge.png';
  static const String typePushup = 'assets/type/pushup.jpg';
  static const String typeSquat = 'assets/type/squat.png';
}
